# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_analysis.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'audio_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61udio_analysis.proto\x12\x05\x61udio\"<\n\x11\x41nalyzeWavRequest\x12\x15\n\rwav_file_path\x18\x01 \x01(\t\x12\x10\n\x08wav_data\x18\x02 \x01(\x0c\"\x94\x02\n\x12\x41udioFeaturesReply\x12\r\n\x05tempo\x18\x01 \x01(\x02\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x12\n\nkey_number\x18\x03 \x01(\x05\x12\x0c\n\x04mode\x18\x04 \x01(\t\x12\x13\n\x0bmode_number\x18\x05 \x01(\x05\x12\x0e\n\x06\x65nergy\x18\x06 \x01(\x02\x12\x14\n\x0c\x64\x61nceability\x18\x07 \x01(\x02\x12\x14\n\x0c\x61\x63ousticness\x18\x08 \x01(\x02\x12\x19\n\x11spectral_centroid\x18\t \x01(\x02\x12\x1a\n\x12zero_crossing_rate\x18\n \x01(\x02\x12\x10\n\x08\x64uration\x18\x0b \x01(\x02\x12\x13\n\x0b\x63hroma_mean\x18\x0c \x03(\x02\x12\x11\n\tmfcc_mean\x18\r \x03(\x02\x32R\n\rAudioAnalyzer\x12\x41\n\nAnalyzeWav\x12\x18.audio.AnalyzeWavRequest\x1a\x19.audio.AudioFeaturesReplyB\x08\xaa\x02\x05\x41udiob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\005Audio'
  _globals['_ANALYZEWAVREQUEST']._serialized_start=31
  _globals['_ANALYZEWAVREQUEST']._serialized_end=91
  _globals['_AUDIOFEATURESREPLY']._serialized_start=94
  _globals['_AUDIOFEATURESREPLY']._serialized_end=370
  _globals['_AUDIOANALYZER']._serialized_start=372
  _globals['_AUDIOANALYZER']._serialized_end=454
# @@protoc_insertion_point(module_scope)
