name: CI/CD Pipeline

on:
 pull_request: 
  branches:
   - main

jobs:
 build-and-push-image:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout source
    uses: actions/checkout@v4

  - name: Get latest Git tag
    id: get_tag
    run: |
      TAG=$(git describe --tags --abbrev=0)
      echo "Latest tag is $TAG"
      echo "tag=$TAG" >> $GITHUB_OUTPUT
    
  - name: Log in Dockerhub
    uses: docker/login-action@v3
    with:
     username: ${{ secrets.DOCKERHUB_USERNAME }}
     password: ${{ secrets.DOCKERHUB_PAT }}
     
  - name: Build and push Docker image
    uses: docker/build-push-action@v6
    with:
     context: .
     file: ./Dockerfile
     push: true
     tags: |
      ${{ secrets.DOCKERHUB_REPO_NAME }}:latest
      ${{ secrets.DOCKERHUB_REPO_NAME }}:${{ steps.get_tag.outputs.tag }}
     
 pull-and-deploy:
  runs-on: ubuntu-latest
  steps:
  - name: Install ssh keys
    run: |
     install -m 600 -D /dev/null ~/.ssh/id_rsa
     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
     ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    
  # sync env file from Infisical
  - name: Sync env from Infisical
    run: |
     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
      cd ${{ secrets.WORKDIR }} 
      infisical export --silent --token=${{ secrets.INFISICAL_TOKEN }} > .env
     "

  # pull image from hub and run command
  - name: Docker jobs [Login - Pull - Run - Logout]
    run: |
     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
      cd ${{ secrets.WORKDIR }} 
      echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      docker pull ${{ secrets.DOCKER_IMAGE }}
      docker-compose down
      docker-compose up -d
      docker logout
     "

  #clean ssh session 
  - name: Clean up ssh session
    run: rm -rf ~/.ssh
