name: CI/CD Pipeline

on:
 push: 
  branches:
   - main

jobs:
 setup-ssh:
  runs-on: ubuntu-latest
  steps:
  - name: Install ssh keys
    run: |
     install -m 600 -D /dev/null ~/.ssh/id_rsa
     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
     ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
  - name: Connect & change directory 
    run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
    
 sync-env:
  needs: setup-ssh
  runs-on: ubuntu-latest
  steps:
  - name: Sync env from Infisical
    run: |
     cd ${{ secrets.ENV_FOLDER }} 
     infisical export --silent --token=${{ secrets.INFISICAL_TOKEN }} > .env

 docker-job:
  needs: sync-env
  runs-on: ubuntu-latest
  steps:
  - name: Login Docker hub
    run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  - name: Pull image from docker hub
    run: docker pull ${{ secrets.DOCKER_IMAGE }}
  - name: Rerun docker
    run: |
     cd ..
     docker-compose up -d

 clean-up-ssh:
  needs: docker-job
  runs-on: ubuntu-latest
  steps:
  - name: Clean up
    run: rm -rf ~/.ssh
